package com.spring.pojo;

import java.util.Date;

public class UserLoginStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_login_status.uuid
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_login_status.uid
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_login_status.account_name
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_login_status.login_time
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_login_status.uuid
     *
     * @return the value of us_login_status.uuid
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_login_status.uuid
     *
     * @param uuid the value for us_login_status.uuid
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_login_status.uid
     *
     * @return the value of us_login_status.uid
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_login_status.uid
     *
     * @param uid the value for us_login_status.uid
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_login_status.account_name
     *
     * @return the value of us_login_status.account_name
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_login_status.account_name
     *
     * @param accountName the value for us_login_status.account_name
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_login_status.login_time
     *
     * @return the value of us_login_status.login_time
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_login_status.login_time
     *
     * @param loginTime the value for us_login_status.login_time
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}