package com.spring.mapper;

import com.spring.pojo.UserLoginStatus;
import com.spring.pojo.UserLoginStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int countByExample(UserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int deleteByExample(UserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int insert(UserLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int insertSelective(UserLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    List<UserLoginStatus> selectByExample(UserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    UserLoginStatus selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") UserLoginStatus record, @Param("example") UserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int updateByExample(@Param("record") UserLoginStatus record, @Param("example") UserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(UserLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_login_status
     *
     * @mbggenerated Thu Mar 10 12:39:29 GMT+08:00 2016
     */
    int updateByPrimaryKey(UserLoginStatus record);
}